version: "3"
services:
  app:
    build: app/
    ports: 
      - "8000:8000"
    container_name: containerize_app_1
  nginx:
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - nginx/files/:/etc/nginx/
    container_name: containerize_nginx_1
    depends_on:
       - nodeapp